from __future__ import annotations

import json
import sys
import tarfile
from contextlib import nullcontext
from hashlib import sha256
from io import BytesIO
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
SCRIPTS = ROOT / "scripts"
for path in (SRC, SCRIPTS):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import backup_config as bc  # noqa: E402
import ci_preflight  # noqa: E402
import ci_no_test_policy  # noqa: E402
import pack_full_wiki_tar  # noqa: E402
import sync_huggingface  # noqa: E402
import validate_graph_artifacts as vga  # noqa: E402
from ctx import dashboard_entities  # noqa: E402
from ctx.core.wiki import wiki_queue_worker  # noqa: E402
from ctx.utils._secret_scan import find_inline_secret_arg  # noqa: E402


class _FakeCommitInfo:
    commit_url = "https://huggingface.co/datasets/Stevesolun/ctx/commit/card"


class _FakeHfApi:
    def __init__(self) -> None:
        self.calls: list[tuple[str, dict[str, Any]]] = []

    def upload_folder(self, **kwargs: Any) -> _FakeCommitInfo:
        self.calls.append(("upload_folder", kwargs))
        return _FakeCommitInfo()


def _add_tar_text(tf: tarfile.TarFile, name: str, text: str) -> None:
    payload = text.encode("utf-8")
    info = tarfile.TarInfo(name)
    info.size = len(payload)
    tf.addfile(info, BytesIO(payload))


def test_artifact_promotion_retry_allows_completed_promotion_recovery(tmp_path: Path) -> None:
    wiki = tmp_path / "wiki"
    target = wiki / "graphify-out" / "graph.json"
    target.parent.mkdir(parents=True)
    payload = b'{"nodes":[]}\n'
    target.write_bytes(payload)
    staged = target.with_name(f"{target.name}.staged")
    metadata = target.with_name(f"{target.name}.promotion.json")
    metadata.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "status": "staged",
                "target": str(target),
                "previous": {},
                "candidate": {"sha256": sha256(payload).hexdigest()},
            }
        ),
        encoding="utf-8",
    )

    message = wiki_queue_worker._handle_artifact_promotion(
        wiki,
        {
            "staged_path": staged.name,
            "target_path": "graphify-out/graph.json",
        },
    )

    assert message == f"promoted artifact to {target}"
    assert json.loads(metadata.read_text(encoding="utf-8"))["status"] == "promoted"


def test_from_ctx_config_ignores_malformed_user_top_files(
    monkeypatch: Any,
    tmp_path: Path,
    capsys: Any,
) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("USERPROFILE", str(tmp_path))
    claude_dir = tmp_path / ".claude"
    claude_dir.mkdir()
    (claude_dir / "backup-config.json").write_text(
        json.dumps({"top_files": ["safe.json", "../secret.json", "nested/file.json"]}),
        encoding="utf-8",
    )

    cfg = bc.from_ctx_config()

    assert cfg.top_files == ("safe.json",)
    assert "ignoring top_files entry" in capsys.readouterr().err


def test_from_ctx_config_fails_closed_when_user_top_files_all_invalid(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("USERPROFILE", str(tmp_path))
    claude_dir = tmp_path / ".claude"
    claude_dir.mkdir()
    (claude_dir / "backup-config.json").write_text(
        json.dumps({"top_files": ["../secret.json", "nested/file.json"]}),
        encoding="utf-8",
    )

    cfg = bc.from_ctx_config()

    assert cfg.top_files == bc.BackupConfig().top_files


def test_host_user_path_redaction_covers_paths_with_spaces() -> None:
    text = (
        "POSIX `/Users/steves/My Project/wiki page.md`\n"
        "Windows C:\\Users\\steves\\My Project\\wiki page.md\n"
    )

    redacted = pack_full_wiki_tar._redact_host_user_paths(text)

    assert "/Users/" not in redacted
    assert "C:\\Users" not in redacted
    assert "My Project" not in redacted
    assert redacted.count("<host-user-path>") == 2


def test_host_user_path_redaction_covers_terminal_spaced_component() -> None:
    text = (
        "/Users/steves/My Project\n"
        "/Users/steves/my project\n"
        "/home/steves/lower case dir\n"
        "`/Users/steves/lower case dir`\n"
    )

    redacted = pack_full_wiki_tar._redact_host_user_paths(text)

    assert redacted == (
        "<host-user-path>\n<host-user-path>\n<host-user-path>\n`<host-user-path>`\n"
    )


def test_host_user_path_redaction_preserves_trailing_prose() -> None:
    redacted = pack_full_wiki_tar._redact_host_user_paths(
        "/Users/steves/ctx generated by worker\n"
        "/Users/steves/ctx for details\n"
        "/Users/steves/my project, generated by worker\n"
    )

    assert redacted == (
        "<host-user-path> generated by worker\n"
        "<host-user-path> for details\n"
        "<host-user-path>, generated by worker\n"
    )


def test_secret_arg_indirection_validates_env_reference_values() -> None:
    assert find_inline_secret_arg(["--token-env=secret-value"]) == "--token-env"
    assert (
        find_inline_secret_arg(["--token-env=ghp_abcdefghijklmnopqrstuvwxyz123456"])
        == "--token-env"
    )
    assert find_inline_secret_arg(["--token-env", "secret-value"]) == "--token-env"
    assert find_inline_secret_arg(["--token-env=ABCDEF1234567890"]) == "--token-env"
    assert find_inline_secret_arg(["--token_env=GITHUB_TOKEN"]) is None
    assert find_inline_secret_arg(["--api_key_path=/run/secrets/openai"]) is None
    assert find_inline_secret_arg(["--api-key-path", "hunter2"]) == "--api-key-path"
    assert find_inline_secret_arg(["--api-key-file=secret-value"]) == "--api-key-file"
    assert find_inline_secret_arg(["--api_key_path=./secrets/openai"]) is None
    assert find_inline_secret_arg(["--api-key-path=${OPENAI_API_KEY_PATH}"]) is None


def test_no_test_policy_treats_no_mistakes_config_as_contract_file() -> None:
    result = ci_no_test_policy.evaluate_policy(
        [".no-mistakes.yaml"],
        (),
        {".no-mistakes.yaml": "+commands: changed\n"},
    )

    assert result.passed is False
    assert result.contract_files == (".no-mistakes.yaml",)


def test_host_user_path_redaction_covers_key_value_delimiters() -> None:
    text = (
        "cwd=/Users/steves/ctx\nsource:/home/steves/wiki\nurl=https://example.com/home/user-guide\n"
        "User: /validate /home/user/webapp --vuln-type command_injection\n"
        "Binary: /home/user/binary_app/build/vuln\n"
        "Rule: No `/home/` hardcoded path prefixes\n"
    )

    redacted = pack_full_wiki_tar._redact_host_user_paths(text)

    assert "/Users/" not in redacted
    assert "/home/steves" not in redacted
    assert "/home/user/" not in redacted
    assert "`/home/`" not in redacted
    assert "https://example.com/home/user-guide" in redacted
    assert redacted.count("<host-user-path>") == 5


@pytest.mark.parametrize(
    "payload",
    [
        b"cwd=/Users/steves/ctx\n",
        b"source:/home/steves/wiki\n",
        b"path,C:\\Users\\steves\\ctx\n",
        b"path,C:\\users\\steves\\ctx\n",
        b"path,C:/users/steves/ctx\n",
        b"url=file:///C:/Users/alice/ctx\n",
    ],
)
def test_graph_markdown_host_path_scan_covers_key_value_delimiters(payload: bytes) -> None:
    with pytest.raises(vga.GraphArtifactError, match="archive markdown contains host path"):
        vga._validate_archive_markdown_payload("log.md", payload, context="archive")


@pytest.mark.parametrize(
    "workflow_path",
    [
        ".github/workflows/huggingface-sync.yml",
        ".github/workflows/publish.yml",
        ".github/workflows/test.yml",
    ],
)
def test_graph_workflow_searches_release_cache_before_lfs_fallback(
    workflow_path: str,
) -> None:
    workflow = (ROOT / workflow_path).read_text(encoding="utf-8")
    resolve_script = workflow[workflow.index("def hydrate_from_release") :]

    release_search = resolve_script.index("for release in load_releases():")
    lfs_fallback = resolve_script.rindex(
        "hydrate_from_lfs(path_name, expected_oid, expected_size, hydrated_min_size)"
    )

    assert release_search < lfs_fallback
    assert (
        "hydrate_from_lfs(path_name, expected_oid, expected_size, hydrated_min_size)"
        not in resolve_script[:release_search]
    )
    assert 'if expected_oid != fallback["sha256"]' not in resolve_script


def test_preflight_refuses_oversized_graph_lfs_pointer_before_pull(
    monkeypatch: Any,
    tmp_path: Path,
    capsys: Any,
) -> None:
    monkeypatch.setattr(ci_preflight, "REPO_ROOT", tmp_path)
    artifact = tmp_path / "graph" / "wiki-graph.tar.gz"
    artifact.parent.mkdir()
    max_size = ci_preflight.GRAPH_LFS_MAX_FALLBACK_SIZES["graph/wiki-graph.tar.gz"]
    artifact.write_text(
        f"version https://git-lfs.github.com/spec/v1\noid sha256:{'a' * 64}\nsize {max_size + 1}\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(ci_preflight.shutil, "which", lambda _name: "/usr/bin/git")

    def fail_run(*_args: Any, **_kwargs: Any) -> None:
        raise AssertionError("git lfs pull should not run")

    monkeypatch.setattr(ci_preflight.subprocess, "run", fail_run)

    assert ci_preflight.hydrate_graph_lfs_artifacts() == 1
    assert "exceeds cap" in capsys.readouterr().err


def test_hf_card_export_uploads_docs_and_changelog(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    export_dir = tmp_path / "export"
    (repo / "docs").mkdir(parents=True)
    export_dir.mkdir()
    (repo / "README.md").write_text("# ctx\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("# Changelog\n", encoding="utf-8")
    (repo / "docs" / "guide.md").write_text("# Guide\n", encoding="utf-8")
    monkeypatch.setattr(
        sync_huggingface,
        "_iter_tracked_files",
        lambda _repo: [
            Path("README.md"),
            Path("CHANGELOG.md"),
            Path("docs/guide.md"),
            Path("src/not-card.py"),
        ],
    )

    sync_huggingface._export_card_inputs(repo, export_dir)

    assert (export_dir / "README.md").read_text(encoding="utf-8").startswith("---\nlicense: mit\n")
    assert (export_dir / "CHANGELOG.md").read_text(encoding="utf-8") == "# Changelog\n"
    assert (export_dir / "docs" / "guide.md").read_text(encoding="utf-8") == "# Guide\n"
    assert not (export_dir / "src").exists()

    api = _FakeHfApi()
    url = sync_huggingface._upload_card_inputs(
        api=api,
        export_dir=export_dir,
        repo_id="Stevesolun/ctx",
        repo_type="dataset",
        head="abcdef1234567890",
    )

    assert url == "https://huggingface.co/datasets/Stevesolun/ctx/commit/card"
    assert api.calls == [
        (
            "upload_folder",
            {
                "repo_id": "Stevesolun/ctx",
                "repo_type": "dataset",
                "folder_path": str(export_dir),
                "commit_message": "Sync ctx card abcdef1",
                "commit_description": "GitHub commit: abcdef1234567890",
                "delete_patterns": list(sync_huggingface.CARD_ONLY_DELETE_PATTERNS),
            },
        )
    ]


def test_hf_export_rejects_raw_tracked_symlink(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    export_dir = tmp_path / "export"
    docs = repo / "docs"
    docs.mkdir(parents=True)
    export_dir.mkdir()
    (repo / "guide-source.md").write_text("# Guide\n", encoding="utf-8")
    (docs / "guide.md").symlink_to(repo / "guide-source.md")

    with pytest.raises(ValueError, match="refusing to follow symlink"):
        sync_huggingface._copy_export_file(
            repo.resolve(),
            export_dir.resolve(),
            Path("docs/guide.md"),
        )


def test_hf_card_sync_checks_repo_stats_before_export(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    calls: list[str] = []

    class FakeApi:
        def __init__(self, *, token: str) -> None:
            calls.append(f"api:{token}")

    fake_hub = type(sys)("huggingface_hub")
    setattr(fake_hub, "HfApi", FakeApi)
    monkeypatch.setitem(sys.modules, "huggingface_hub", fake_hub)
    monkeypatch.setattr(
        sync_huggingface,
        "_git",
        lambda _repo, *_args: "abcdef1234567890",
    )
    monkeypatch.setattr(
        sync_huggingface,
        "_assert_repo_stats_current",
        lambda _repo: calls.append("stats"),
    )

    def fake_export(_repo: Path, _export_dir: Path) -> None:
        calls.append("export")

    monkeypatch.setattr(sync_huggingface, "_export_card_inputs", fake_export)
    monkeypatch.setattr(
        sync_huggingface,
        "_ensure_hf_repo_exists",
        lambda **_kwargs: calls.append("ensure"),
    )

    def fake_upload(**_kwargs: Any) -> str:
        calls.append("upload")
        return "https://example.test/commit"

    monkeypatch.setattr(
        sync_huggingface,
        "_upload_card_inputs",
        fake_upload,
    )

    url = sync_huggingface.sync_card_to_huggingface(
        repo=tmp_path,
        repo_id="Stevesolun/ctx",
        repo_type="dataset",
        token="hf-token",
    )

    assert url == "https://example.test/commit"
    assert calls == ["stats", "export", "api:hf-token", "ensure", "upload"]


def test_mcp_env_placeholders_do_not_expand_credentials_into_argv_by_default(
    monkeypatch: Any,
) -> None:
    from ctx.adapters.generic.tools import McpServerConfig, mcp_router

    monkeypatch.setenv("MCP_API_KEY", "argv-only-secret")
    cfg = McpServerConfig(
        name="argvserver",
        command="server",
        args=("--api-key", "${MCP_API_KEY}", "--header=Bearer $MCP_API_KEY"),
        credential_env=("MCP_API_KEY",),
    )

    env = mcp_router._child_env_for_config(cfg)

    with pytest.raises(ValueError, match="sensitive env var 'MCP_API_KEY'"):
        mcp_router._expand_config_args(cfg, env)
    assert cfg.args[1] == "${MCP_API_KEY}"


def test_mcp_env_placeholder_expansion_checks_option_context() -> None:
    from ctx.adapters.generic.tools import McpServerConfig, mcp_router

    cfg = McpServerConfig(
        name="argvserver",
        command="server",
        args=("--api-key", "${OPENAI_KEY}"),
        env={"OPENAI_KEY": "argv-only-secret"},
    )

    with pytest.raises(ValueError, match="secret-looking argument '--api-key'"):
        mcp_router._expand_config_args(cfg, mcp_router._child_env_for_config(cfg))


def test_mcp_env_placeholder_expansion_rejects_bearer_header() -> None:
    from ctx.adapters.generic.tools import McpServerConfig, mcp_router

    cfg = McpServerConfig(
        name="argvserver",
        command="server",
        args=("--header=Bearer ${MCP_AUTH}",),
        env={"MCP_AUTH": "headersecret"},
    )

    with pytest.raises(ValueError, match="secret-looking argument 'Bearer'"):
        mcp_router._expand_config_args(cfg, mcp_router._child_env_for_config(cfg))


def test_artifact_promotion_rejects_repo_graph_target_from_untrusted_project(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    host_project = tmp_path / "host-project"
    wiki = tmp_path / "wiki"
    target = host_project / "graph" / "wiki-graph-stats.json"
    staged = target.with_name(f"{target.name}.staged")
    installed_worker = host_project / ".venv" / "site-packages" / "ctx" / "core" / "wiki"
    target.parent.mkdir(parents=True)
    installed_worker.mkdir(parents=True)
    staged.write_text("{}", encoding="utf-8")
    (host_project / "pyproject.toml").write_text(
        '[project]\nname = "not-ctx"\n',
        encoding="utf-8",
    )
    fake_source = installed_worker / "wiki_queue_worker.py"
    fake_source.write_text("# installed worker\n", encoding="utf-8")
    monkeypatch.setattr(wiki_queue_worker, "__file__", str(fake_source))

    assert wiki_queue_worker._source_root() is None

    with pytest.raises(ValueError, match="not an allowed artifact target"):
        wiki_queue_worker._resolve_artifact_promotion_paths(
            wiki,
            str(staged),
            str(target),
        )


def test_repack_full_wiki_tar_redacts_graph_json_host_paths(tmp_path: Path) -> None:
    source = tmp_path / "wiki-graph.tar.gz"
    target = tmp_path / "wiki-graph-packed.tar.gz"
    with tarfile.open(source, "w:gz") as tf:
        _add_tar_text(tf, "index.md", "# Wiki\n")
        _add_tar_text(
            tf,
            "entities/skills/example.md",
            "# Example\n",
        )
        _add_tar_text(
            tf,
            "graphify-out/graph-export-manifest.json",
            json.dumps({"export_id": "test-export"}),
        )
        _add_tar_text(
            tf,
            "graphify-out/graph.json",
            json.dumps(
                {
                    "graph": {"export_id": "test-export"},
                    "nodes": [
                        {
                            "id": "skill:example",
                            "source_keys": ["/Users/steves/ctx/entities/skills/example.md"],
                        }
                    ],
                    "edges": [],
                }
            ),
        )

    pack_full_wiki_tar.repack_full_wiki_tar(source, target)

    with tarfile.open(target, "r:gz") as tf:
        graph_payload = tf.extractfile("graphify-out/graph.json")
        assert graph_payload is not None
        graph_json = graph_payload.read().decode("utf-8")
    assert "/Users/" not in graph_json
    assert "<host-user-path>" in graph_json


def test_graph_validation_rejects_host_paths_in_graph_json() -> None:
    payload = json.dumps(
        {
            "graph": {"export_id": "test-export"},
            "nodes": [
                {
                    "id": "skill:example",
                    "source_keys": ["/Users/steves/ctx/entities/skills/example.md"],
                }
            ],
            "edges": [],
        }
    ).encode("utf-8")

    with pytest.raises(vga.GraphArtifactError, match="graph.json contains host path"):
        vga._scan_graph_json(BytesIO(payload))


def test_full_archive_contract_requires_wiki_pack_and_rejects_expanded_markdown(
    tmp_path: Path,
) -> None:
    with pytest.raises(vga.GraphArtifactError, match="missing wiki-packs"):
        vga._validate_wiki_pack_payload(set(), tmp_path, expected_export_id="test-export")

    with pytest.raises(vga.GraphArtifactError, match="expanded markdown member"):
        vga._validate_archive_markdown_payload(
            "entities/skills/example.md",
            b"# Example\n",
            context="archive",
        )


def test_artifact_promotion_uses_target_validator_for_json_without_payload_validator(
    tmp_path: Path,
) -> None:
    wiki = tmp_path / "wiki"
    target = wiki / "graphify-out" / "graph.json"
    staged = target.with_name("graph.json.staged")
    target.parent.mkdir(parents=True)
    target.write_text('{"nodes":[],"edges":[],"graph":{}}\n', encoding="utf-8")
    staged.write_text("not-json\n", encoding="utf-8")

    with pytest.raises(ValueError, match="invalid JSON artifact"):
        wiki_queue_worker._handle_artifact_promotion(
            wiki,
            {
                "staged_path": "graphify-out/graph.json.staged",
                "target_path": "graphify-out/graph.json",
                "validator": "none",
            },
        )
    assert target.read_text(encoding="utf-8") == '{"nodes":[],"edges":[],"graph":{}}\n'
    assert staged.exists()


def test_artifact_promotion_uses_target_validator_for_tar_without_payload_validator(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    target = repo / "graph" / "wiki-graph-runtime.tar.gz"
    staged = target.with_name("wiki-graph-runtime.tar.gz.staged")
    target.parent.mkdir(parents=True)
    target.write_bytes(b"old-tar")
    staged.write_bytes(b"not-a-tar")
    monkeypatch.setattr(wiki_queue_worker, "_source_root", lambda: repo.resolve())

    with pytest.raises(ValueError, match="invalid tar.gz artifact"):
        wiki_queue_worker._handle_artifact_promotion(
            tmp_path / "wiki",
            {
                "staged_path": str(staged),
                "target_path": str(target),
            },
        )
    assert target.read_bytes() == b"old-tar"
    assert staged.exists()


def test_artifact_promotion_rejects_incomplete_runtime_tar_without_payload_validator(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    target = repo / "graph" / "wiki-graph-runtime.tar.gz"
    staged = target.with_name("wiki-graph-runtime.tar.gz.staged")
    target.parent.mkdir(parents=True)
    target.write_bytes(b"old-tar")
    payload = b'{"graph":{"export_id":"export-test"},"nodes":[],"edges":[]}'
    info = tarfile.TarInfo("graphify-out/graph.json")
    info.size = len(payload)
    with tarfile.open(staged, "w:gz") as tf:
        tf.addfile(info, BytesIO(payload))
    monkeypatch.setattr(wiki_queue_worker, "_source_root", lambda: repo.resolve())

    with pytest.raises(ValueError, match="invalid runtime graph artifact"):
        wiki_queue_worker._handle_artifact_promotion(
            tmp_path / "wiki",
            {
                "staged_path": str(staged),
                "target_path": str(target),
            },
        )
    assert target.read_bytes() == b"old-tar"
    assert staged.exists()


def test_entity_search_fallback_returns_wiki_relative_path(tmp_path: Path) -> None:
    wiki = tmp_path / "wiki"
    entity_path = wiki / "entities" / "skills" / "python-patterns.md"
    entity_path.parent.mkdir(parents=True)
    entity_path.write_text("# Python Patterns\n", encoding="utf-8")
    deps = dashboard_entities.EntityCrudDeps(
        is_safe_slug=lambda _value: True,
        normalize_entity_type=lambda value: "skill" if value in (None, "skill") else None,
        wiki_entity_detail=lambda _slug, _etype: None,
        wiki_entity_target_path=lambda slug, _etype: wiki / f"{slug}.md",
        wiki_entity_path=lambda _slug, _etype: entity_path,
        iter_wiki_entity_paths=lambda _etype: [("python-patterns", "skill", entity_path)],
        wiki_relative_path=lambda path: path.relative_to(wiki).as_posix(),
        read_manifest=lambda: {"load": []},
        perform_unload=lambda _slug, _etype: (True, "unloaded"),
        queue_entity_refresh=lambda *_args: None,
        file_lock=lambda _path: nullcontext(),
        write_entity_text=lambda _path, _content: None,
        parse_frontmatter=lambda text: ({}, text),
        frontmatter_tags=lambda _value: [],
        frontmatter_text=lambda value: str(value or ""),
        display_slug=lambda value: value,
        display_label=lambda value: str(value),
        entity_wiki_href=lambda slug, _etype: f"/wiki/{slug}?type=skill",
        scan_skill_content=lambda _slug, _content: (True, "ok"),
    )

    results = dashboard_entities.search_wiki_entities("patterns", "skill", deps=deps)

    assert results[0]["path"] == "entities/skills/python-patterns.md"
    assert str(tmp_path) not in results[0]["path"]


def test_lfs_pointer_probe_does_not_full_read_hydrated_artifact(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    artifact = tmp_path / "graph" / "wiki-graph.tar.gz"
    artifact.parent.mkdir()
    artifact.write_bytes(b"hydrated graph payload")

    def fail_read_bytes(_path: Path) -> bytes:
        raise AssertionError("read_bytes should not be used for prefix probing")

    monkeypatch.setattr(Path, "read_bytes", fail_read_bytes)

    assert ci_preflight._read_lfs_pointer(artifact) is None
