"""Client-side graph explorer script for ctx-monitor."""

from __future__ import annotations


def render_graph_client_script(*, focus_js: str, focus_type_js: str) -> str:
    """Return the dependency-free client script for the graph explorer."""
    return (
        "<script>\n"
        f"const initial = {focus_js};\n"
        f"const initialType = {focus_type_js};\n"
        "const cyMount = document.getElementById('cy');\n"
        "const focus = document.getElementById('focus');\n"
        "const focusType = document.getElementById('focus-type');\n"
        "const liveSearchBox = document.getElementById('graph-live-results');\n"
        "let liveSearchTimer = null;\n"
        "let liveSearchAbort = null;\n"
        "let currentGraphQuery = null;\n"
        "let graphReturnStack = [];\n"
        "let pendingDrillKey = '';\n"
        "let graphLoadSeq = 0;\n"
        "function nodeColor(type) {\n"
        "  if (type === 'agent') return '#f59e0b';\n"
        "  if (type === 'mcp-server') return '#ef4444';\n"
        "  if (type === 'harness') return '#22c55e';\n"
        "  return '#6366f1';\n"
        "}\n"
        "function escapeHtml(s) { return String(s).replace(/[&<>\"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[ch])); }\n"
        "function dataAttr(el, name) { return el.getAttribute(name) || ''; }\n"
        "function fmtCount(n) { return Number(n || 0).toLocaleString(); }\n"
        "function rawNodeSlug(id) { return String(id || '').replace(/^(skill|agent|mcp-server|harness):/, ''); }\n"
        "function displaySlug(slug) { return String(slug || '').replace(/^skills-sh-/, ''); }\n"
        "function nodeSlug(id) { return displaySlug(rawNodeSlug(id)); }\n"
        "function nodeDomId(id) { return 'graph-node-' + String(id || '').replace(/[^a-zA-Z0-9_-]/g, '_'); }\n"
        "function graphQueryKey(q) { return q ? (String(q.slug || '') + '|' + String(q.type || '')) : ''; }\n"
        "function sameGraphQuery(a, b) { return graphQueryKey(a) === graphQueryKey(b); }\n"
        "function graphQueryFromNodeData(d) { return {slug: rawNodeSlug(d.id), type: d.type || ''}; }\n"
        "function graphQueryFromPayload(g, requestedSlug, requestedType) {\n"
        "  const centerId = g.center || '';\n"
        "  const centerData = (g.nodes || []).map(n => n.data || {}).find(d => d.id === centerId) || {};\n"
        "  const resolved = g.resolved || {};\n"
        "  return {slug: resolved.slug || requestedSlug || rawNodeSlug(centerId), type: resolved.type || centerData.type || requestedType || ''};\n"
        "}\n"
        "function wikiHref(data) {\n"
        "  const nodeType = data.type || '';\n"
        "  const suffix = nodeType ? '?type=' + encodeURIComponent(nodeType) : '';\n"
        "  return '/wiki/' + encodeURIComponent(rawNodeSlug(data.id)) + suffix;\n"
        "}\n"
        "function renderFallback(g) {\n"
        "  const nodes = g.nodes || [];\n"
        "  const rows = nodes.map(n => {\n"
        "    const d = n.data || {};\n"
        "    const tags = Array.from(d.filter_tokens || d.tags || []).join(' ');\n"
        "    const typeKey = ['skill', 'agent', 'mcp-server', 'harness'].includes(d.type) ? d.type : 'entity';\n"
        "    return '<a data-testid=\"graph-fallback-node\" class=\"graph-fallback-node\" '\n"
        "      + 'data-node-id=\"' + escapeHtml(d.id || '') + '\" '\n"
        "      + 'data-slug=\"' + escapeHtml(nodeSlug(d.id)) + '\" '\n"
        "      + 'data-type=\"' + escapeHtml(d.type || '') + '\" '\n"
        "      + 'data-depth=\"' + escapeHtml(d.depth || 0) + '\" '\n"
        "      + 'data-tags=\"' + escapeHtml(tags.toLowerCase()) + '\" '\n"
        "      + 'href=\"' + escapeHtml(wikiHref(d)) + '\" '\n"
        "      + 'style=\"display:flex; justify-content:space-between; gap:0.75rem; padding:0.45rem 0.6rem; border-bottom:1px solid #e5e7eb; color:inherit; text-decoration:none;\">'\n"
        "      + '<span class=\"graph-fallback-label\">' + escapeHtml(d.label || nodeSlug(d.id)) + '</span>'\n"
        "      + '<span class=\"pill entity-type-' + escapeHtml(typeKey) + '\">' + escapeHtml(d.type || 'entity') + '</span></a>';\n"
        "  }).join('');\n"
        "  cyMount.innerHTML = '<div data-testid=\"graph-fallback\" style=\"padding:0.75rem; height:100%; overflow:auto;\">'\n"
        "    + '<div class=\"muted\" style=\"margin-bottom:0.5rem;\">Showing list view.</div>'\n"
        "    + rows + '</div>';\n"
        "}\n"
        "function nodeDetail(d) {\n"
        "  const tags = Array.from(d.tags || []).join(', ') || 'none';\n"
        "  const size = d.node_size == null ? 'auto' : Number(d.node_size).toFixed(1);\n"
        "  const sizeReason = d.size_reason ? ' - size: ' + size + ' (' + d.size_reason + ')' : ' - size: ' + size;\n"
        "  const desc = d.description ? ' - ' + d.description : '';\n"
        "  return (d.label || nodeSlug(d.id)) + ' - ' + (d.type || 'entity') + desc + ' - tags: ' + tags + ' - quality: ' + qualityText(d.quality_score) + ' - usage: ' + usageText(d.usage_score) + sizeReason;\n"
        "}\n"
        "function nodeRadius(d, isCenter, scale) {\n"
        "  const base = Math.max(isCenter ? 14 : 8, Math.min(24, Number(d.node_size || (isCenter ? 16 : 11))));\n"
        "  const perspective = Math.max(0.8, Math.min(1.2, Number(scale || 1)));\n"
        "  return Math.max(8, Math.min(28, base * perspective));\n"
        "}\n"
        "function polygonPoints(cx, cy, points) {\n"
        "  return points.map(p => (cx + p[0]).toFixed(1) + ',' + (cy + p[1]).toFixed(1)).join(' ');\n"
        "}\n"
        "function nodeShapeSvg(d, p, r) {\n"
        "  const fill = nodeColor(d.type);\n"
        "  const common = ' data-testid=\"graph-svg-node\" data-node-shape=\"' + escapeHtml(d.type || 'skill') + '\" data-radius=\"' + r.toFixed(1) + '\" fill=\"' + fill + '\" stroke=\"#fff\" stroke-width=\"2\"';\n"
        "  if (d.type === 'agent') {\n"
        "    return '<polygon' + common + ' points=\"' + polygonPoints(p.x, p.y, [[0, -r], [r, 0], [0, r], [-r, 0]]) + '\" />';\n"
        "  }\n"
        "  if (d.type === 'mcp-server') {\n"
        "    const side = (r * 1.62).toFixed(1);\n"
        "    return '<rect' + common + ' x=\"' + (p.x - r * 0.81).toFixed(1) + '\" y=\"' + (p.y - r * 0.81).toFixed(1) + '\" width=\"' + side + '\" height=\"' + side + '\" rx=\"4\" />';\n"
        "  }\n"
        "  if (d.type === 'harness') {\n"
        "    return '<polygon' + common + ' points=\"' + polygonPoints(p.x, p.y, [[0, -r], [r * 0.87, -r * 0.5], [r * 0.87, r * 0.5], [0, r], [-r * 0.87, r * 0.5], [-r * 0.87, -r * 0.5]]) + '\" />';\n"
        "  }\n"
        "  return '<circle' + common + ' cx=\"' + p.x.toFixed(1) + '\" cy=\"' + p.y.toFixed(1) + '\" r=\"' + r + '\" />';\n"
        "}\n"
        "function edgeDetail(d) {\n"
        "  const tags = Array.from(d.shared_tags || []).join(', ') || 'none';\n"
        "  const reasons = Array.from(d.reasons || d.edge_reasons || []).join(', ') || (edgeHasEvidence(d) ? 'graph signal' : 'none');\n"
        "  const prefix = isWeakGraphOnlyEdge(d) ? 'Low-confidence auto link: ' : 'Relationship: ';\n"
        "  return prefix + nodeSlug(d.source) + ' <-> ' + nodeSlug(d.target) + ' - ' + edgeStrengthText(d) + ' - shared: ' + tags + ' - evidence: ' + reasons;\n"
        "}\n"
        "function graphExplanation(g) {\n"
        "  const e = g.explanations || {};\n"
        "  return [e.focus, e.source, e.search, e.layout, e.edges].filter(Boolean).join(' ');\n"
        "}\n"
        "let currentGraphState = null;\n"
        "let currentGraphEdges = [];\n"
        "function numericValue(value) {\n"
        "  if (value == null || value === '') return null;\n"
        "  const n = Number(value);\n"
        "  return Number.isFinite(n) ? n : null;\n"
        "}\n"
        "function clampedUnit(value) {\n"
        "  const n = numericValue(value);\n"
        "  if (n == null) return null;\n"
        "  return Math.max(0, Math.min(1, n));\n"
        "}\n"
        "function percentText(value) {\n"
        "  const n = clampedUnit(value);\n"
        "  return n == null ? 'unknown' : Math.round(n * 100) + '%';\n"
        "}\n"
        "function qualityText(value) {\n"
        "  const raw = numericValue(value);\n"
        "  if (raw == null) return 'not scored yet';\n"
        "  const suffix = raw < 0 || raw > 1 ? ' (raw score clamped)' : '';\n"
        "  return percentText(raw) + suffix;\n"
        "}\n"
        "function usageText(value) {\n"
        "  return numericValue(value) == null ? 'no telemetry yet' : percentText(value);\n"
        "}\n"
        "function scoreText(value) {\n"
        "  return clampedUnit(value) == null ? 'unknown' : percentText(value);\n"
        "}\n"
        "function currentMatchWindow() {\n"
        "  const minInput = document.getElementById('match-filter-min');\n"
        "  const maxInput = document.getElementById('match-filter-max');\n"
        "  const matchA = Math.max(0, Math.min(100, Number(minInput?.value || 0)));\n"
        "  const matchB = Math.max(0, Math.min(100, Number(maxInput?.value || 100)));\n"
        "  const lowPct = Math.min(matchA, matchB);\n"
        "  const highPct = Math.max(matchA, matchB);\n"
        "  return {lowPct, highPct, min: lowPct / 100, max: highPct / 100};\n"
        "}\n"
        "function renderMatchRange(matchWindow) {\n"
        "  document.getElementById('match-filter-min-value').textContent = Math.round(matchWindow.lowPct) + '%';\n"
        "  document.getElementById('match-filter-max-value').textContent = Math.round(matchWindow.highPct) + '%';\n"
        "  const fill = document.getElementById('match-range-fill');\n"
        "  if (fill) {\n"
        "    fill.style.left = matchWindow.lowPct + '%';\n"
        "    fill.style.width = Math.max(0, matchWindow.highPct - matchWindow.lowPct) + '%';\n"
        "  }\n"
        "}\n"
        "function setMatchWindow(lowPct, highPct) {\n"
        "  const minInput = document.getElementById('match-filter-min');\n"
        "  const maxInput = document.getElementById('match-filter-max');\n"
        "  if (!minInput || !maxInput) return;\n"
        "  minInput.value = String(Math.max(0, Math.min(100, Number(lowPct || 0))));\n"
        "  maxInput.value = String(Math.max(0, Math.min(100, Number(highPct || 100))));\n"
        "  applyFilters();\n"
        "}\n"
        "function renderMatchHistogram(edges, matchWindow) {\n"
        "  const box = document.getElementById('match-histogram');\n"
        "  if (!box) return;\n"
        "  const bins = Array(10).fill(0);\n"
        "  (edges || []).forEach(edge => {\n"
        "    const d = edge.data || edge || {};\n"
        "    const weight = clampedUnit(d.weight);\n"
        "    if (weight == null) return;\n"
        "    const idx = Math.min(9, Math.max(0, Math.floor(Math.min(100, weight * 100) / 10)));\n"
        "    bins[idx] += 1;\n"
        "  });\n"
        "  const maxBin = Math.max(1, ...bins);\n"
        "  box.innerHTML = bins.map((count, idx) => {\n"
        "    const start = idx * 10;\n"
        "    const end = idx === 9 ? 100 : idx * 10 + 9;\n"
        "    const active = end >= matchWindow.lowPct && start <= matchWindow.highPct;\n"
        "    const height = Math.max(10, Math.round((count / maxBin) * 100));\n"
        "    const label = start + '-' + end + '%: ' + fmtCount(count) + ' relationships';\n"
        "    return '<button type=\"button\" class=\"graph-match-bar' + (active ? ' active' : '') + '\" '\n"
        "      + 'data-match-bin-min=\"' + start + '\" data-match-bin-max=\"' + end + '\" '\n"
        "      + 'aria-label=\"Filter match ' + label + '\" title=\"' + label + '\" '\n"
        "      + 'style=\"height:' + height + '%\"></button>';\n"
        "  }).join('');\n"
        "  box.querySelectorAll('[data-match-bin-min]').forEach(bar => {\n"
        "    const useBin = () => setMatchWindow(bar.dataset.matchBinMin, bar.dataset.matchBinMax);\n"
        "    bar.addEventListener('click', useBin);\n"
        "    bar.addEventListener('keydown', ev => {\n"
        "      if (ev.key !== 'Enter' && ev.key !== ' ') return;\n"
        "      ev.preventDefault();\n"
        "      useBin();\n"
        "    });\n"
        "  });\n"
        "}\n"
        "function metricChip(label, value) {\n"
        "  const n = numericValue(value);\n"
        "  if (n == null || n <= 0) return '';\n"
        "  return '<span class=\"graph-metric\"><strong>' + escapeHtml(label) + '</strong> ' + escapeHtml(scoreText(value)) + '</span>';\n"
        "}\n"
        "function edgeHasEvidence(edge) {\n"
        "  const d = edge || {};\n"
        "  const shared = Array.from(d.shared_tags || []);\n"
        "  const reasons = Array.from(d.reasons || d.edge_reasons || []);\n"
        "  return shared.length > 0 || reasons.length > 0\n"
        "    || Number(d.semantic || 0) > 0 || Number(d.tag_sim || 0) > 0\n"
        "    || Number(d.slug_token_sim || 0) > 0 || Number(d.source_overlap || 0) > 0;\n"
        "}\n"
        "function isGraphOnlyEdge(edge) {\n"
        "  return !edgeHasEvidence(edge || {});\n"
        "}\n"
        "function isWeakGraphOnlyEdge(edge) {\n"
        "  const d = edge || {};\n"
        "  return Number(d.weight || 0) < 0.15 && isGraphOnlyEdge(d);\n"
        "}\n"
        "function edgeStrengthText(edge) {\n"
        "  const d = edge || {};\n"
        "  const weight = clampedUnit(d.weight) == null ? 'unknown' : percentText(d.weight);\n"
        "  if (isGraphOnlyEdge(d)) return weight + ' graph neighbor';\n"
        "  return weight + ' relation strength';\n"
        "}\n"
        "function edgeSignalHtml(edge) {\n"
        "  const d = edge || {};\n"
        "  const shared = Array.from(d.shared_tags || []);\n"
        "  const reasons = Array.from(d.reasons || d.edge_reasons || []);\n"
        "  if (isGraphOnlyEdge(d)) {\n"
        "    return '<div class=\"graph-edge-signals\"><span class=\"graph-metric\"><strong>match</strong> '\n"
        "      + escapeHtml(percentText(d.weight)) + '</span></div>';\n"
        "  }\n"
        "  const evidence = reasons.length ? reasons.join(', ') : (edgeHasEvidence(d) ? 'graph signal' : 'none');\n"
        "  return '<div class=\"graph-edge-signals\">'\n"
        "    + '<span class=\"graph-metric\"><strong>strength</strong> ' + escapeHtml(edgeStrengthText(d)) + '</span>'\n"
        "    + metricChip('semantic', d.semantic)\n"
        "    + metricChip('tag', d.tag_sim)\n"
        "    + metricChip('slug', d.slug_token_sim)\n"
        "    + metricChip('source', d.source_overlap)\n"
        "    + '</div>'\n"
        "    + '<div class=\"muted\">shared: ' + escapeHtml(shared.join(', ') || 'none')\n"
        "    + ' - evidence: ' + escapeHtml(evidence) + '</div>';\n"
        "}\n"
        "function buildGraphState(nodes, edges) {\n"
        "  const nodesById = new Map();\n"
        "  const adjacency = new Map();\n"
        "  nodes.forEach(n => {\n"
        "    const d = n.data || {};\n"
        "    if (!d.id) return;\n"
        "    nodesById.set(d.id, d);\n"
        "    adjacency.set(d.id, []);\n"
        "  });\n"
        "  edges.forEach(e => {\n"
        "    const d = e.data || {};\n"
        "    const source = nodesById.get(d.source);\n"
        "    const target = nodesById.get(d.target);\n"
        "    if (!source || !target) return;\n"
        "    adjacency.get(d.source).push({node: target, edge: d});\n"
        "    adjacency.get(d.target).push({node: source, edge: d});\n"
        "  });\n"
        "  adjacency.forEach(items => items.sort((a, b) => Number(b.edge.weight || 0) - Number(a.edge.weight || 0)));\n"
        "  return {nodesById, adjacency};\n"
        "}\n"
        "function nodeSummaryHtml(d) {\n"
        "  const tags = Array.from(d.tags || []);\n"
        "  return '<div class=\"graph-selected-summary\">'\n"
        "    + '<div><strong>' + escapeHtml(d.label || nodeSlug(d.id)) + '</strong> '\n"
        "    + '<span class=\"pill entity-type-' + escapeHtml(d.type || 'skill') + '\">' + escapeHtml(d.type || 'entity') + '</span></div>'\n"
        "    + '<a href=\"' + escapeHtml(wikiHref(d)) + '\">open wiki</a>'\n"
        "    + '<div class=\"muted\">Connections: ' + fmtCount(d.degree) + ' in graph - quality: ' + escapeHtml(qualityText(d.quality_score))\n"
        "    + ' - usage: ' + escapeHtml(usageText(d.usage_score)) + '</div>'\n"
        "    + '<div class=\"muted\">tags: ' + escapeHtml(tags.join(', ') || 'none') + '</div>'\n"
        "    + (d.description ? '<p>' + escapeHtml(d.description) + '</p>' : '')\n"
        "    + '</div>';\n"
        "}\n"
        "function renderNodeTree(nodeId) {\n"
        "  if (!currentGraphState) return '<div class=\"muted\">No graph loaded.</div>';\n"
        "  const d = currentGraphState.nodesById.get(nodeId);\n"
        "  if (!d) return '<div class=\"muted\">Node not found in this view.</div>';\n"
        "  const neighbors = currentGraphState.adjacency.get(nodeId) || [];\n"
        "  const visibleNeighbors = neighbors;\n"
        "  const groups = new Map();\n"
        "  visibleNeighbors.forEach(item => {\n"
        "    const type = item.node.type || 'entity';\n"
        "    if (!groups.has(type)) groups.set(type, []);\n"
        "    groups.get(type).push(item);\n"
        "  });\n"
        "  const groupsHtml = Array.from(groups.entries()).map(([type, items]) => {\n"
        "    const rows = items.map(item => {\n"
        "      const n = item.node;\n"
        "      const inner = (currentGraphState.adjacency.get(n.id) || [])\n"
        "        .filter(rel => rel.node.id !== nodeId)\n"
        "        .slice(0, 8);\n"
        "      const innerHtml = inner.length ? '<details class=\"graph-inner-links\"><summary>'\n"
        "        + fmtCount(inner.length) + ' in-view links</summary><ul>'\n"
        "        + inner.map(rel => '<li><span class=\"graph-link-label\">' + escapeHtml(n.label || nodeSlug(n.id)) + '</span> -> <span class=\"graph-link-label\">'\n"
        "          + escapeHtml(rel.node.label || nodeSlug(rel.node.id)) + '</span> '\n"
        "          + '<span class=\"muted\">' + escapeHtml(scoreText(rel.edge.weight)) + '</span></li>').join('')\n"
        "        + '</ul></details>' : '';\n"
        "      return '<li class=\"graph-neighbor-item\">'\n"
        "        + '<div class=\"graph-neighbor-row\"><span><span class=\"graph-neighbor-label\">' + escapeHtml(n.label || nodeSlug(n.id)) + '</span> '\n"
        "        + '<span class=\"pill entity-type-' + escapeHtml(n.type || 'skill') + '\">' + escapeHtml(n.type || 'entity') + '</span></span>'\n"
        "        + '<a href=\"' + escapeHtml(wikiHref(n)) + '\">wiki</a></div>'\n"
        "        + edgeSignalHtml(item.edge)\n"
        "        + innerHtml\n"
        "        + '</li>';\n"
        "    }).join('');\n"
        "    return '<details class=\"graph-neighbor-group\" open><summary>' + escapeHtml(type) + ' (' + fmtCount(items.length) + ')</summary><ul>' + rows + '</ul></details>';\n"
        "  }).join('');\n"
        "  return '<div class=\"graph-neighbor-tree\">' + nodeSummaryHtml(d)\n"
        "    + '<h3>Neighbors</h3>'\n"
        "    + (groupsHtml || '<p class=\"muted\">No neighbors in this view.</p>')\n"
        "    + '</div>';\n"
        "}\n"
        "function renderGraph3d(g) {\n"
        "  const nodes = g.nodes || [];\n"
        "  const edges = g.edges || [];\n"
        "  if (!nodes.length) { renderFallback(g); return; }\n"
        "  currentGraphState = buildGraphState(nodes, edges);\n"
        "  currentGraphEdges = edges;\n"
        "  const width = Math.max(640, Math.floor(cyMount.clientWidth || 800));\n"
        "  const height = Math.max(420, Math.floor(cyMount.clientHeight || 520));\n"
        "  const center = nodes.find(n => (n.data || {}).depth === 0) || nodes[0];\n"
        "  const centerId = (center.data || {}).id;\n"
        "  let selectedNodeId = centerId;\n"
        "  const points = new Map([[centerId, {x: 0, y: 0, z: 0}]]);\n"
        "  const others = nodes.filter(n => (n.data || {}).id !== centerId);\n"
        "  others.forEach((n, idx) => {\n"
        "    const d = n.data || {};\n"
        "    const i = idx + 1;\n"
        "    const phi = Math.acos(1 - 2 * i / Math.max(2, others.length + 1));\n"
        "    const theta = Math.PI * (3 - Math.sqrt(5)) * i;\n"
        "    const depth = Math.max(1, Number(d.depth || 1));\n"
        "    const radius = 180 + depth * 90;\n"
        "    points.set(d.id, {x: radius * Math.cos(theta) * Math.sin(phi), y: radius * Math.sin(theta) * Math.sin(phi), z: radius * Math.cos(phi)});\n"
        "  });\n"
        "  cyMount.innerHTML = '<div data-testid=\"graph-renderer\" class=\"graph-renderer-shell\">'\n"
        "    + '<div class=\"graph-toolbar\">'\n"
        "    + '<button id=\"graph-zoom-in\" type=\"button\">zoom +</button><button id=\"graph-zoom-out\" type=\"button\">zoom -</button>'\n"
        "    + '<span class=\"muted\">drag rotate - wheel zoom - click drill - double-click back</span></div>'\n"
        "    + '<div class=\"graph-canvas-wrap\"><svg data-testid=\"graph-3d\" viewBox=\"0 0 ' + width + ' ' + height + '\" style=\"display:block; width:100%; height:100%; min-height:0; background:transparent; touch-action:none;\"></svg><div id=\"graph-tooltip\" class=\"graph-tooltip\" hidden></div></div>'\n"
        "    + '<div data-testid=\"graph-inspector-resize\" class=\"graph-resize-handle\" role=\"separator\" tabindex=\"0\" aria-orientation=\"horizontal\" aria-label=\"Resize graph details panel\" title=\"Drag to resize details panel; double-click to reset\"></div>'\n"
        "    + '<div class=\"graph-inspector-grid\">'\n"
        "    + '<div data-testid=\"graph-node-detail\" class=\"graph-node-detail-panel\"><div data-testid=\"graph-edge-detail\" class=\"muted graph-edge-detail-inline\">Hover an edge for relationship signals.</div><div data-testid=\"graph-node-detail-tree\" class=\"muted\">Click a node to inspect neighbors.</div></div></div>'\n"
        "    + '<div data-testid=\"graph-list\" class=\"graph-list-panel\" hidden></div></div>';\n"
        "  const rendererShell = cyMount.querySelector('[data-testid=\"graph-renderer\"]');\n"
        "  const svg = cyMount.querySelector('[data-testid=\"graph-3d\"]');\n"
        "  const resizeHandle = cyMount.querySelector('[data-testid=\"graph-inspector-resize\"]');\n"
        "  const nodeDetailBox = cyMount.querySelector('[data-testid=\"graph-node-detail-tree\"]');\n"
        "  const edgeDetailBox = cyMount.querySelector('[data-testid=\"graph-edge-detail\"]');\n"
        "  const tooltip = cyMount.querySelector('#graph-tooltip');\n"
        "  const inspectorStorageKey = 'ctx-monitor-graph-inspector-height';\n"
        "  function clampInspectorHeight(value) {\n"
        "    const shellRect = rendererShell.getBoundingClientRect();\n"
        "    const toolbar = cyMount.querySelector('.graph-toolbar');\n"
        "    const toolbarHeight = toolbar ? toolbar.getBoundingClientRect().height : 42;\n"
        "    const min = 140;\n"
        "    const max = Math.max(min, shellRect.height - toolbarHeight - 300);\n"
        "    return Math.max(min, Math.min(max, Number(value) || 0));\n"
        "  }\n"
        "  function setInspectorHeight(value, persist = true) {\n"
        "    const heightPx = clampInspectorHeight(value);\n"
        "    rendererShell.style.setProperty('--graph-inspector-height', heightPx + 'px');\n"
        "    resizeHandle.setAttribute('aria-valuenow', String(Math.round(heightPx)));\n"
        "    resizeHandle.setAttribute('aria-valuemin', '140');\n"
        "    if (persist) {\n"
        "      try { localStorage.setItem(inspectorStorageKey, String(Math.round(heightPx))); } catch (_) {}\n"
        "    }\n"
        "  }\n"
        "  function resetInspectorHeight() {\n"
        "    rendererShell.style.removeProperty('--graph-inspector-height');\n"
        "    resizeHandle.removeAttribute('aria-valuenow');\n"
        "    try { localStorage.removeItem(inspectorStorageKey); } catch (_) {}\n"
        "  }\n"
        "  try {\n"
        "    const savedInspectorHeight = Number(localStorage.getItem(inspectorStorageKey));\n"
        "    if (Number.isFinite(savedInspectorHeight) && savedInspectorHeight > 0) setInspectorHeight(savedInspectorHeight, false);\n"
        "  } catch (_) {}\n"
        "  resizeHandle.addEventListener('pointerdown', ev => {\n"
        "    ev.preventDefault();\n"
        "    rendererShell.classList.add('graph-resizing');\n"
        "    resizeHandle.setPointerCapture(ev.pointerId);\n"
        "    const onMove = moveEv => {\n"
        "      const shellRect = rendererShell.getBoundingClientRect();\n"
        "      setInspectorHeight(shellRect.bottom - moveEv.clientY);\n"
        "    };\n"
        "    const onUp = upEv => {\n"
        "      rendererShell.classList.remove('graph-resizing');\n"
        "      try { resizeHandle.releasePointerCapture(upEv.pointerId); } catch (_) {}\n"
        "      resizeHandle.removeEventListener('pointermove', onMove);\n"
        "      resizeHandle.removeEventListener('pointerup', onUp);\n"
        "      resizeHandle.removeEventListener('pointercancel', onUp);\n"
        "    };\n"
        "    resizeHandle.addEventListener('pointermove', onMove);\n"
        "    resizeHandle.addEventListener('pointerup', onUp);\n"
        "    resizeHandle.addEventListener('pointercancel', onUp);\n"
        "  });\n"
        "  resizeHandle.addEventListener('keydown', ev => {\n"
        "    const current = Number(getComputedStyle(rendererShell).getPropertyValue('--graph-inspector-height').replace('px', '')) || cyMount.querySelector('.graph-inspector-grid').getBoundingClientRect().height;\n"
        "    if (ev.key === 'ArrowUp') { ev.preventDefault(); setInspectorHeight(current + 28); }\n"
        "    if (ev.key === 'ArrowDown') { ev.preventDefault(); setInspectorHeight(current - 28); }\n"
        "    if (ev.key === 'Home') { ev.preventDefault(); resetInspectorHeight(); }\n"
        "  });\n"
        "  resizeHandle.addEventListener('dblclick', resetInspectorHeight);\n"
        "  let yaw = -0.4;\n"
        "  let pitch = 0.55;\n"
        "  let zoom = 1;\n"
        "  function project(p) {\n"
        "    const cyaw = Math.cos(yaw), syaw = Math.sin(yaw);\n"
        "    const cp = Math.cos(pitch), sp = Math.sin(pitch);\n"
        "    const x1 = p.x * cyaw - p.z * syaw;\n"
        "    const z1 = p.x * syaw + p.z * cyaw;\n"
        "    const y1 = p.y * cp - z1 * sp;\n"
        "    const z2 = p.y * sp + z1 * cp;\n"
        "    const scale = zoom * 600 / (720 + z2);\n"
        "    return {x: width / 2 + x1 * scale, y: height / 2 + y1 * scale, z: z2, scale};\n"
        "  }\n"
        "  function showTooltip(text, ev) {\n"
        "    tooltip.textContent = text || '';\n"
        "    tooltip.hidden = !text;\n"
        "    const rect = cyMount.getBoundingClientRect();\n"
        "    tooltip.style.left = Math.min(rect.width - 260, Math.max(8, ev.clientX - rect.left + 12)) + 'px';\n"
        "    tooltip.style.top = Math.max(8, ev.clientY - rect.top + 12) + 'px';\n"
        "  }\n"
        "  function hideTooltip() { tooltip.hidden = true; }\n"
        "  function highlightSelected() {\n"
        "    svg.querySelectorAll('[data-3d-node-id]').forEach(n => {\n"
        "      n.classList.toggle('graph-node-selected', dataAttr(n, 'data-3d-node-id') === selectedNodeId);\n"
        "    });\n"
        "    const edgeEls = new Set([...svg.querySelectorAll('[data-testid=\"graph-svg-edge\"]')]);\n"
        "    edgeEls.forEach(e => {\n"
        "      const source = dataAttr(e, 'data-3d-edge-source') || dataAttr(e, 'data-svg-edge-source');\n"
        "      const target = dataAttr(e, 'data-3d-edge-target') || dataAttr(e, 'data-svg-edge-target');\n"
        "      e.classList.toggle('graph-edge-selected', source === selectedNodeId || target === selectedNodeId);\n"
        "    });\n"
        "  }\n"
        "  function focusCameraOnNode(nodeId) {\n"
        "    const p = points.get(nodeId);\n"
        "    if (!p) return;\n"
        "    if (nodeId !== centerId) {\n"
        "      yaw = Math.atan2(-p.z, Math.max(1, p.x));\n"
        "      pitch = Math.max(-1.1, Math.min(1.1, Math.atan2(p.y, Math.max(120, Math.hypot(p.x, p.z)))));\n"
        "    }\n"
        "    zoom = Math.max(zoom, 1.45);\n"
        "    drawGraph3d();\n"
        "  }\n"
        "  function selectNode(nodeId, shouldFocus = true) {\n"
        "    if (!nodeId) return;\n"
        "    selectedNodeId = nodeId;\n"
        "    nodeDetailBox.innerHTML = renderNodeTree(nodeId);\n"
        "    if (shouldFocus) focusCameraOnNode(nodeId);\n"
        "    highlightSelected();\n"
        "  }\n"
        "  let nodeClickTimer = null;\n"
        "  let lastNodeDoubleClickAt = 0;\n"
        "  function selectNodeElement(node) {\n"
        "    if (!node) return;\n"
        "    const id = dataAttr(node, 'data-3d-node-id');\n"
        "    const d = currentGraphState.nodesById.get(id) || {};\n"
        "    if (d.id) drillIntoNode(d.id); else selectNode(id);\n"
        "  }\n"
        "  function scheduleNodeClick(node) {\n"
        "    if (nodeClickTimer) clearTimeout(nodeClickTimer);\n"
        "    nodeClickTimer = setTimeout(() => {\n"
        "      nodeClickTimer = null;\n"
        "      selectNodeElement(node);\n"
        "    }, 300);\n"
        "  }\n"
        "  function handleNodeDoubleClick() {\n"
        "    const now = Date.now();\n"
        "    if (now - lastNodeDoubleClickAt < 250) return;\n"
        "    lastNodeDoubleClickAt = now;\n"
        "    graphLoadSeq += 1;\n"
        "    if (nodeClickTimer) {\n"
        "      clearTimeout(nodeClickTimer);\n"
        "      nodeClickTimer = null;\n"
        "    }\n"
        "    restorePreviousGraph();\n"
        "  }\n"
        "  function drillIntoNode(nodeId) {\n"
        "    if (!nodeId || !currentGraphState) return;\n"
        "    const d = currentGraphState.nodesById.get(nodeId) || {};\n"
        "    if (!d.id) return;\n"
        "    selectNode(d.id, true);\n"
        "    const query = graphQueryFromNodeData(d);\n"
        "    if (!query.slug || sameGraphQuery(currentGraphQuery, query)) return;\n"
        "    const key = graphQueryKey(query);\n"
        "    if (pendingDrillKey === key) return;\n"
        "    pendingDrillKey = key;\n"
        "    load(query.slug, query.type, {pushCurrent: true}).finally(() => {\n"
        "      if (pendingDrillKey === key) pendingDrillKey = '';\n"
        "    });\n"
        "  }\n"
        "  function restorePreviousGraph() {\n"
        "    const previous = graphReturnStack.pop();\n"
        "    if (!previous || !previous.slug) return;\n"
        "    load(previous.slug, previous.type || '', {pushCurrent: false});\n"
        "  }\n"
        "  window.ctxGraphSelectNodeFromElement = (el) => {\n"
        "    const node = el && el.closest ? el.closest('[data-3d-node-id]') : null;\n"
        "    selectNodeElement(node || el);\n"
        "  };\n"
        "  function attach3dHoverHandlers() {\n"
        "    svg.querySelectorAll('[data-node-detail]').forEach(n => {\n"
        "      n.addEventListener('mousemove', ev => showTooltip(n.dataset.nodeDetail || '', ev));\n"
        "      n.addEventListener('mouseleave', hideTooltip);\n"
        "      n.addEventListener('click', ev => {\n"
        "        ev.preventDefault();\n"
        "        ev.stopPropagation();\n"
        "        if (ev.detail && ev.detail > 1) { handleNodeDoubleClick(); return; }\n"
        "        scheduleNodeClick(n);\n"
        "      });\n"
        "      n.addEventListener('dblclick', ev => {\n"
        "        ev.preventDefault();\n"
        "        ev.stopPropagation();\n"
        "        handleNodeDoubleClick();\n"
        "      });\n"
        "      n.addEventListener('keydown', ev => {\n"
        "        if (ev.key !== 'Enter' && ev.key !== ' ') return;\n"
        "        ev.preventDefault();\n"
        "        scheduleNodeClick(n);\n"
        "      });\n"
        "    });\n"
        "    svg.querySelectorAll('[data-testid=\"graph-svg-node\"]').forEach(circle => {\n"
        "      circle.addEventListener('click', ev => {\n"
        "        ev.preventDefault();\n"
        "        ev.stopPropagation();\n"
        "        const node = ev.target.closest ? ev.target.closest('[data-3d-node-id]') : ev.target.parentNode;\n"
        "        if (ev.detail && ev.detail > 1) { handleNodeDoubleClick(); return; }\n"
        "        scheduleNodeClick(node);\n"
        "      });\n"
        "      circle.addEventListener('dblclick', ev => {\n"
        "        ev.preventDefault();\n"
        "        ev.stopPropagation();\n"
        "        handleNodeDoubleClick();\n"
        "      });\n"
        "    });\n"
        "    svg.querySelectorAll('[data-edge-detail]').forEach(e => {\n"
        "      e.addEventListener('mouseenter', () => { edgeDetailBox.textContent = e.dataset.edgeDetail || ''; });\n"
        "      e.addEventListener('mousemove', ev => showTooltip(e.dataset.edgeDetail || '', ev));\n"
        "      e.addEventListener('mouseleave', hideTooltip);\n"
        "    });\n"
        "  }\n"
        "  function drawGraph3d() {\n"
        "    const projected = new Map();\n"
        "    points.forEach((p, id) => projected.set(id, project(p)));\n"
        "    const edgeHtml = edges.map(e => {\n"
        "      const d = e.data || {};\n"
        "      const s = projected.get(d.source);\n"
        "      const t = projected.get(d.target);\n"
        "      if (!s || !t) return '';\n"
        "      const w = Math.max(0.8, Math.min(2.2, 0.75 + Math.sqrt(Math.max(0, Number(d.weight || 0.4))) * 0.85));\n"
        "      return '<line data-testid=\"graph-svg-edge\" data-3d-edge-source=\"' + escapeHtml(d.source || '') + '\" data-3d-edge-target=\"' + escapeHtml(d.target || '') + '\" data-svg-edge-source=\"' + escapeHtml(d.source || '') + '\" data-svg-edge-target=\"' + escapeHtml(d.target || '') + '\" data-edge-weight=\"' + escapeHtml(Number(d.weight || 0).toFixed(4)) + '\" x1=\"' + s.x.toFixed(1) + '\" y1=\"' + s.y.toFixed(1) + '\" x2=\"' + t.x.toFixed(1) + '\" y2=\"' + t.y.toFixed(1) + '\" stroke=\"#64748b\" stroke-opacity=\"' + (0.35 + Math.min(0.4, Number(d.weight || 0) / 3)).toFixed(2) + '\" stroke-width=\"' + w.toFixed(2) + '\" />';\n"
        "    }).join('');\n"
        "    const nodeHtml = nodes.slice().sort((a, b) => (projected.get((a.data || {}).id)?.z || 0) - (projected.get((b.data || {}).id)?.z || 0)).map(n => {\n"
        "      const d = n.data || {};\n"
        "      const p = projected.get(d.id) || {x: width / 2, y: height / 2, z: 0, scale: 1};\n"
        "      const tags = Array.from(d.filter_tokens || d.tags || []).join(' ');\n"
        "      const label = d.label || nodeSlug(d.id);\n"
        "      const isCenter = d.id === centerId;\n"
        "      const r = nodeRadius(d, isCenter, p.scale);\n"
        "      return '<g data-testid=\"graph-3d-node\" role=\"button\" tabindex=\"0\" id=\"' + escapeHtml(nodeDomId(d.id)) + '\" data-3d-node-id=\"' + escapeHtml(d.id || '') + '\" data-node-detail=\"' + escapeHtml(nodeDetail(d)) + '\" data-type=\"' + escapeHtml(d.type || '') + '\" data-depth=\"' + escapeHtml(d.depth || 0) + '\" data-tags=\"' + escapeHtml(tags.toLowerCase()) + '\"><title>' + escapeHtml(nodeDetail(d)) + '</title>' + nodeShapeSvg(d, p, r) + '<text x=\"' + p.x.toFixed(1) + '\" y=\"' + (p.y + r + 14).toFixed(1) + '\" text-anchor=\"middle\" font-size=\"11\" fill=\"#111827\" style=\"pointer-events:none;\">' + escapeHtml(label).slice(0, 28) + '</text></g>';\n"
        "    }).join('');\n"
        "    const edgeHitHtml = edges.map(e => {\n"
        "      const d = e.data || {};\n"
        "      const s = projected.get(d.source);\n"
        "      const t = projected.get(d.target);\n"
        "      if (!s || !t) return '';\n"
        "      const hx1 = s.x + (t.x - s.x) * 0.18, hy1 = s.y + (t.y - s.y) * 0.18;\n"
        "      const hx2 = s.x + (t.x - s.x) * 0.82, hy2 = s.y + (t.y - s.y) * 0.82;\n"
        "      return '<line data-testid=\"graph-3d-edge\" data-3d-edge-source=\"' + escapeHtml(d.source || '') + '\" data-3d-edge-target=\"' + escapeHtml(d.target || '') + '\" data-svg-edge-source=\"' + escapeHtml(d.source || '') + '\" data-svg-edge-target=\"' + escapeHtml(d.target || '') + '\" data-edge-weight=\"' + escapeHtml(Number(d.weight || 0).toFixed(4)) + '\" data-edge-detail=\"' + escapeHtml(edgeDetail(d)) + '\" x1=\"' + hx1.toFixed(1) + '\" y1=\"' + hy1.toFixed(1) + '\" x2=\"' + hx2.toFixed(1) + '\" y2=\"' + hy2.toFixed(1) + '\" stroke=\"transparent\" stroke-width=\"12\" style=\"pointer-events:stroke;\"><title>' + escapeHtml(edgeDetail(d)) + '</title></line>';\n"
        "    }).join('');\n"
        "    svg.innerHTML = '<rect width=\"100%\" height=\"100%\" fill=\"transparent\" pointer-events=\"all\" />' + edgeHtml + edgeHitHtml + nodeHtml;\n"
        "    attach3dHoverHandlers();\n"
        "    applyFilters();\n"
        "    highlightSelected();\n"
        "  }\n"
        "  document.getElementById('graph-zoom-in').addEventListener('click', () => { zoom = Math.min(2.5, zoom * 1.18); drawGraph3d(); });\n"
        "  document.getElementById('graph-zoom-out').addEventListener('click', () => { zoom = Math.max(0.35, zoom / 1.18); drawGraph3d(); });\n"
        "  let dragging = false, lastX = 0, lastY = 0;\n"
        "  svg.addEventListener('pointerdown', ev => {\n"
        "    if (ev.target.closest && ev.target.closest('[data-3d-node-id], [data-edge-detail]')) return;\n"
        "    dragging = true; lastX = ev.clientX; lastY = ev.clientY; svg.setPointerCapture(ev.pointerId);\n"
        "  });\n"
        "  svg.addEventListener('pointerup', ev => { dragging = false; try { svg.releasePointerCapture(ev.pointerId); } catch (_) {} });\n"
        "  svg.addEventListener('pointermove', ev => { if (!dragging) return; yaw += (ev.clientX - lastX) * 0.01; pitch += (ev.clientY - lastY) * 0.01; pitch = Math.max(-1.35, Math.min(1.35, pitch)); lastX = ev.clientX; lastY = ev.clientY; drawGraph3d(); });\n"
        "  svg.addEventListener('wheel', ev => { ev.preventDefault(); zoom = Math.max(0.35, Math.min(2.5, zoom * (ev.deltaY < 0 ? 1.08 : 0.92))); drawGraph3d(); }, {passive:false});\n"
        "  drawGraph3d();\n"
        "  selectNode(centerId, false);\n"
        "}\n"
        "cyMount.innerHTML = '<div data-testid=\"graph-empty\" class=\"muted\" style=\"padding:0.75rem;\">Enter a slug to render the graph.</div>';\n"
        # Client-side filtering (type + tag substring).
        "function applyFilters() {\n"
        "  const allowedTypes = new Set(\n"
        "    Array.from(document.querySelectorAll('.graph-type-filter'))\n"
        "      .filter(cb => cb.checked).map(cb => cb.value));\n"
        "  const tagQ = (document.getElementById('tag-filter').value || '')\n"
        "    .trim().toLowerCase();\n"
        "  const matchWindow = currentMatchWindow();\n"
        "  renderMatchRange(matchWindow);\n"
        "  renderMatchHistogram(currentGraphEdges, matchWindow);\n"
        "  const counts = {skill: 0, agent: 0, 'mcp-server': 0, harness: 0};\n"
        "  let visible = 0;\n"
        "  const hiddenIds = new Set();\n"
        "  function edgeInMatchWindow(weight) {\n"
        "    const w = Number(weight || 0);\n"
        "    return w >= matchWindow.min && w <= matchWindow.max;\n"
        "  }\n"
        "  function nodePassesMatch(nodeId, depth) {\n"
        "    if (String(depth || '') === '0' || !currentGraphState) return true;\n"
        "    const links = currentGraphState.adjacency.get(nodeId) || [];\n"
        "    return links.some(item => edgeInMatchWindow(item.edge.weight));\n"
        "  }\n"
        "  function graphNodeHidden(nodeId, type, depth, tagsValue) {\n"
        "    const isFocus = String(depth || '') === '0';\n"
        "    const tags = String(tagsValue || '').split(/\\s+/).map(x => x.toLowerCase());\n"
        "    const typeOk = isFocus || allowedTypes.has(type);\n"
        "    const tagOk = isFocus || !tagQ || tags.some(tag => tag.includes(tagQ));\n"
        "    const matchOk = nodePassesMatch(nodeId, depth);\n"
        "    return !(typeOk && tagOk && matchOk);\n"
        "  }\n"
        "  document.querySelectorAll('[data-testid=\"graph-fallback-node\"]').forEach(n => {\n"
        "    const t = n.dataset.type;\n"
        "    const hidden = graphNodeHidden(n.dataset.nodeId || '', t, n.dataset.depth, n.dataset.tags);\n"
        "    n.style.display = hidden ? 'none' : 'flex';\n"
        "    if (hidden) hiddenIds.add(n.dataset.nodeId || '');\n"
        "    if (!hidden) {\n"
        "      visible++;\n"
        "      if (t in counts) counts[t]++;\n"
        "    }\n"
        "  });\n"
        "  document.querySelectorAll('[data-3d-node-id]').forEach(n => {\n"
        "    const id = dataAttr(n, 'data-3d-node-id');\n"
        "    const t = dataAttr(n, 'data-type');\n"
        "    const hidden = graphNodeHidden(id, t, dataAttr(n, 'data-depth'), dataAttr(n, 'data-tags'));\n"
        "    n.style.display = hidden ? 'none' : '';\n"
        "    if (hidden) hiddenIds.add(id);\n"
        "    if (!hidden) {\n"
        "      visible++;\n"
        "      if (t in counts) counts[t]++;\n"
        "    }\n"
        "  });\n"
        "  const edgeEls = new Set([...document.querySelectorAll('[data-3d-edge-source]'), ...document.querySelectorAll('[data-svg-edge-source]')]);\n"
        "  edgeEls.forEach(e => {\n"
        "    const source = dataAttr(e, 'data-3d-edge-source') || dataAttr(e, 'data-svg-edge-source');\n"
        "    const target = dataAttr(e, 'data-3d-edge-target') || dataAttr(e, 'data-svg-edge-target');\n"
        "    const weight = Number(dataAttr(e, 'data-edge-weight') || 0);\n"
        "    const hidden = hiddenIds.has(source) || hiddenIds.has(target) || !edgeInMatchWindow(weight);\n"
        "    e.style.display = hidden ? 'none' : '';\n"
        "  });\n"
        "  document.getElementById('graph-count-skill').textContent = fmtCount(counts.skill);\n"
        "  document.getElementById('graph-count-agent').textContent = fmtCount(counts.agent);\n"
        "  document.getElementById('graph-count-mcp-server').textContent = fmtCount(counts['mcp-server']);\n"
        "  document.getElementById('graph-count-harness').textContent = fmtCount(counts.harness);\n"
        "  document.getElementById('graph-match-count').textContent = fmtCount(visible) + ' visible';\n"
        "}\n"
        "function hideLiveSearch() {\n"
        "  liveSearchBox.hidden = true;\n"
        "  liveSearchBox.innerHTML = '';\n"
        "}\n"
        "function renderLiveSearchResults(items, query) {\n"
        "  liveSearchBox.hidden = false;\n"
        "  if (!items.length) {\n"
        "    liveSearchBox.innerHTML = '<div class=\"graph-live-empty\">No graph entities match <code>' + escapeHtml(query) + '</code>.</div>';\n"
        "    return;\n"
        "  }\n"
        "  liveSearchBox.innerHTML = items.map(item => {\n"
        "    const tags = Array.from(item.tags || []).slice(0, 4).join(', ');\n"
        "    const title = item.title || item.display_slug || item.slug;\n"
        "    const detail = [item.description, tags ? 'tags: ' + tags : '', item.degree != null ? 'connections ' + fmtCount(item.degree) : '']\n"
        "      .filter(Boolean).join(' - ');\n"
        "    return '<button type=\"button\" class=\"graph-live-result\" data-live-slug=\"' + escapeHtml(item.slug || '') + '\" data-live-type=\"' + escapeHtml(item.type || '') + '\">'\n"
        "      + '<span><code>' + escapeHtml(item.display_slug || item.slug || title) + '</code> '\n"
        "      + '<span class=\"pill entity-type-' + escapeHtml(item.type || 'skill') + '\">' + escapeHtml(item.type || 'entity') + '</span></span>'\n"
        "      + '<small>' + escapeHtml(detail || title) + '</small></button>';\n"
        "  }).join('');\n"
        "  liveSearchBox.querySelectorAll('[data-live-slug]').forEach(btn => {\n"
        "    btn.addEventListener('click', () => {\n"
        "      focus.value = btn.dataset.liveSlug || '';\n"
        "      focusType.value = btn.dataset.liveType || '';\n"
        "      hideLiveSearch();\n"
        "      load(focus.value.trim(), selectedFocusType());\n"
        "    });\n"
        "  });\n"
        "}\n"
        "async function runLiveSearch() {\n"
        "  const query = focus.value.trim();\n"
        "  if (query.length < 2) { hideLiveSearch(); return; }\n"
        "  if (liveSearchAbort) liveSearchAbort.abort();\n"
        "  liveSearchAbort = new AbortController();\n"
        "  liveSearchBox.hidden = false;\n"
        "  liveSearchBox.innerHTML = '<div class=\"graph-live-empty\">Searching...</div>';\n"
        "  const suffix = '';\n"
        "  try {\n"
        "    const r = await fetch('/api/entities/search.json?q=' + encodeURIComponent(query) + suffix + '&limit=12', {signal: liveSearchAbort.signal});\n"
        "    if (!r.ok) throw new Error('search failed');\n"
        "    const payload = await r.json();\n"
        "    renderLiveSearchResults(payload.results || [], query);\n"
        "  } catch (err) {\n"
        "    if (err.name === 'AbortError') return;\n"
        "    liveSearchBox.innerHTML = '<div class=\"graph-live-empty\">Search failed. Press Enter to resolve the slug directly.</div>';\n"
        "  }\n"
        "}\n"
        "function scheduleLiveSearch() {\n"
        "  clearTimeout(liveSearchTimer);\n"
        "  liveSearchTimer = setTimeout(runLiveSearch, 180);\n"
        "}\n"
        "async function load(slug, entityType = '', options = {}) {\n"
        "  if (!slug) return;\n"
        "  hideLiveSearch();\n"
        "  const previousQuery = currentGraphQuery;\n"
        "  const loadSeq = ++graphLoadSeq;\n"
        "  document.getElementById('msg').textContent = 'loading...';\n"
        "  const suffix = entityType ? '?type=' + encodeURIComponent(entityType) : '';\n"
        "  const r = await fetch('/api/graph/' + encodeURIComponent(slug) + '.json' + suffix);\n"
        "  if (loadSeq !== graphLoadSeq) return;\n"
        "  if (!r.ok) { document.getElementById('msg').textContent = 'not found'; return; }\n"
        "  const g = await r.json();\n"
        "  if (loadSeq !== graphLoadSeq) return;\n"
        "  if (!g.center) { document.getElementById('msg').textContent = 'slug not in graph'; return; }\n"
        "  const nextQuery = graphQueryFromPayload(g, slug, entityType);\n"
        "  if (options.pushCurrent && previousQuery && !sameGraphQuery(previousQuery, nextQuery)) {\n"
        "    graphReturnStack.push(previousQuery);\n"
        "  }\n"
        "  currentGraphQuery = nextQuery;\n"
        "  focus.value = nextQuery.slug || slug;\n"
        "  focusType.value = nextQuery.type || entityType || '';\n"
        "  try { renderGraph3d(g); } catch (err) { renderFallback(g); }\n"
        "  const resolved = g.resolved && g.resolved.query !== g.resolved.slug ? ' - showing ' + g.resolved.slug + ' for ' + g.resolved.query : '';\n"
        "  document.getElementById('msg').textContent = fmtCount(g.nodes.length) + ' nodes - ' + fmtCount(g.edges.length) + ' edges' + resolved;\n"
        "  document.getElementById('graph-explanation').textContent = graphExplanation(g);\n"
        "  applyFilters();\n"
        "}\n"
        "function selectedFocusType() { return focusType.value || ''; }\n"
        "document.getElementById('go').addEventListener('click', () => load(focus.value.trim(), selectedFocusType()));\n"
        "focus.addEventListener('input', scheduleLiveSearch);\n"
        "focus.addEventListener('keydown', (ev) => { if (ev.key === 'Enter') load(ev.target.value.trim(), selectedFocusType()); });\n"
        "focusType.addEventListener('change', scheduleLiveSearch);\n"
        "document.querySelectorAll('.graph-type-filter').forEach(cb => cb.addEventListener('change', applyFilters));\n"
        "document.getElementById('match-filter-min').addEventListener('input', applyFilters);\n"
        "document.getElementById('match-filter-max').addEventListener('input', applyFilters);\n"
        "document.getElementById('tag-filter').addEventListener('input', applyFilters);\n"
        "if (initial) load(initial, initialType);\n"
        "</script>"
    )
